- name: Block-Test
  hosts: web1
  gather_facts: false

  tasks:
    - name: Test1
      block:
        - name: Block-1-1
          ansible.builtin.debug:
            msg: 'I execute normally'
          changed_when: true
          notify: Handlers-1-1

        - name: Block-1-2
          ansible.builtin.debug:
            msg: 'I execute normally'
          changed_when: true
          notify: Handlers-1-2

        - name: Block-1-3
          ansible.builtin.command: /bin/false
          changed_when: true
          notify: Handlers-1-3

        - name: Block-1-4
          ansible.builtin.debug:
            msg: 'I execute normally'
          changed_when: true
          notify: Handlers-1-4

      rescue:
        - name: Rescue-1-1
          ansible.builtin.meta: flush_handlers

    - name: Test2
      block:
        - name: Block-2-1
          ansible.builtin.debug:
            msg: 'I execute normally'
          changed_when: true
          notify: Handlers-2-1

        - name: Block-2-2
          ansible.builtin.debug:
            msg: 'I execute normally'
          changed_when: true
          notify: Handlers-2-2

        - name: Block-2-3
          ansible.builtin.debug:
            msg: 'I execute normally'
          changed_when: true
          notify: Handlers-2-3

      rescue:
        - name: Rescue-2-1
          ansible.builtin.meta: flush_handlers

  handlers:
    - name: Handlers-1-1
      ansible.builtin.debug:
        msg: 'This handler runs even on error'

    - name: Handlers-1-2
      ansible.builtin.debug:
        msg: 'This handler runs even on error'

    - name: Handlers-1-3
      ansible.builtin.debug:
        msg: 'This handler runs even on error'

    - name: Handlers-1-4
      ansible.builtin.debug:
        msg: 'This handler runs even on error'

    - name: Handlers-2-1
      ansible.builtin.debug:
        msg: 'This handler runs even on error'

    - name: Handlers-2-2
      ansible.builtin.debug:
        msg: 'This handler runs even on error'

    - name: Handlers-2-3
      ansible.builtin.debug:
        msg: 'This handler runs even on error'
